name: Terraform Tests

on:
  push:
    paths:
      - "modules/webserver_cluster/**"
      - "tests/webserver_cluster/**"
      - ".github/workflows/terraform-test.yml"
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tests/webserver_cluster

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
